name: Auto commit

on:
  push:
    branches:
      - master
      
  schedule:
  - cron: "0 6 * * 1-5"

jobs:
  auto-commit:
  runs-on: ubuntu-latest
  permissions:
    contents: write

  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Make changes
      run: |
        echo "Updated at $(date)" >> update-log.txt

    - name: Configure Git
      run: |
        git config --global user.name "Izzatul Muttaqin"
        git config --global user.email "izzatul.muttaqin@email.com"

    - name: Commit and push
      run: |
        git add .
        git commit -m "chore: auto-update log [skip ci]"
        git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}